### ISSUE TITLE
Setting labels to boolean values results in unexpected behavior

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calicoctl#1448]
I set this label on a workload endpoint:  `{"test": True}`.  

It got rendered as
```
/ # /code/dist/calicoctl get wep -o yaml
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    labels:
      test: "true"
    name: db879d25f656c86857c6846c0d3973d43181dc10dca77334ad6dd2e91a2b4ff7
    node: 4d4b962273c1
    orchestrator: libnetwork
    workload: libnetwork
  spec:
    interfaceName: calidb879d25f65
    ipNetworks:
    - 192.168.210.0/32
    mac: ee:ee:ee:ee:ee:ee
    profiles:
    - testnet2
```
But I was expecting it to be rendered as `{"test": "True"}`, so my rule selector didn't work: `{"selector": "test == 'True'"}`.  

I'm not sure this behaviour is obvious, so perhaps we should simply reject boolean labels rather than converting them?
