### ISSUE TITLE
port forwarding doesn't work on docker 1.12.5 with calico v1.0.2 

### ISSUE THREAD

**Issue by sunilganatra** [projectcalico/calicoctl#1510]
I am trying to forward inbound traffic of host on following ports 22,10000.9443,8443 to calico network container. 

docker's port forwarding is not working as it is. I came across calico document to apply policy on calico-node. I tried to apply following policy but it is not working. could you please comment some examples on how to achieve port forwarding. 

- apiVersion: v1
  kind: policy
  metadata:
    name: port-forwarding
  spec:
    egress:
    - action: allow
    ingress:
    - action: allow
      destination:
        ports:
        - 22
        - 10000
        - 8443
        - 9443
      protocol: tcp
      source:

**Comment by tmjd** [comment]
Ok the first thing I feel I need to point out is that since you are using calico each container is receiving its own IP and doing port forwarding is not necessary since the containers can be reached directly.  If you are accessing the service from hosts that are not running calico node that those hosts will need to have the routes necessary to reach those IP addresses.

Second, I just asked the team I work with and port forwarding is not supported by calico.

With that said the following is a profile and policy that would work to open up the ports you have listed.  You will need a profile defined to set labels that the policy will use and then need to update your policy to use those labels. (Or you can just use profiles)  See http://docs.projectcalico.org/master/getting-started/docker/tutorials/advanced-policy

You need to load a profile similar to the following
```
cat << EOF | calicoctl apply -f -
- apiVersion: v1
  kind: profile
  metadata:
    name: <docker network name created with calico driver flags>
    labels:
      role: <policy label>
EOF
```

Then update your policy with something like
```
cat << EOF | calicoctl apply -f -
- apiVersion: v1
  kind: policy
  metadata:
    name: port-forwarding
  spec:
    selector: role == '<policy label>'
    egress:
    - action: allow
    ingress:
    - action: allow
      destination:
        ports:
        - 22
        - 10000
        - 8443
        - 9443
      protocol: tcp
      source: {}
EOF
```

Please update this issue if this works for you or you need further assistance.
