### ISSUE TITLE
calico/node fails if there are active iptables rules that need plugins

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calicoctl#1518]
Felix runs `iptables-save` to dump the contents of iptables for inspection.  If another process, outside the container, has added a rule that requires a plugin that we don't have inside our container then `iptables-save` fails.

One example is the shaman monitor daemon used in Virtuozzo linux.

**Comment by jaxxstorm** [comment]
Any suggestions on how to rectify this? I've tried:
Mounting `/usr/lib64/xtables` into `/lib/xtables` on the container.
Made sure kernel modules are mounted, and can see the custom module with `lsmod`

It seems iptables isn't picking up the module, as when I run:

```
cat /proc/net/ip_tables_matches
```

I can't see the module loaded.

**Comment by jaxxstorm** [comment]
One option here is to have BIRD and conf running inside a container, then an env var to disable the calico-felix binary.

I opened an issue here to detail instructions on how to get this working as well: https://github.com/projectcalico/felix/issues/1340

**Comment by fasaxc** [comment]
Looks like @jaxxstorm was able to get his particular case working by running Felix outside the container: https://github.com/projectcalico/felix/issues/1340

**Comment by fasaxc** [comment]
Even if we can't solve the root cause, we could have made this easier to diagnose by doing a sanity check of iptables in statup.go.  For example, just run `iptables-save` and bail out with an error if it fails?

**Comment by fasaxc** [comment]
Assigning to @heschlie for triage.

**Comment by caseydavenport** [comment]
We should at least document this behavior - that might be enough to close the issue given nobody else has really hit this?

**Comment by caseydavenport** [comment]
I'm going to close this for now. If we start seeing this pop up more often I'd be happy to reopen.

**Comment by knfoo** [comment]
I have run it to this as well.
I am using the geoip module.
I would like to avoid to run calico-felix binary on the host.

**Comment by fasaxc** [comment]
Not really sure what we an do  about custom modules.  Best option might be for you to build your own calico/node image with the extra module added.

**Comment by fasaxc** [comment]
I guess if there are just one or two modules and they're not large, we could just add them to the main image; is the geoip module packaged for RH?

**Comment by knfoo** [comment]
I installed the xtables-common-addons in ubuntu to get it working.
I "hacked" the calico-node deployment to do

```
        - name: calico-node
          image: calico/node:v3.15.0
          command: ["/usr/bin/bash"]
          args: ['-c', 'if [ ! -f "/usr/lib64/xtables/libxt_geoip.so" ]; then cp /tmp/xtables/libxt_geoip.so /usr/lib64/xtables; start_runit; else start_runit; fi' ]
``` 
And added the right volumes
```
            - name: xtables-addons
              mountPath: /usr/lib/xtables-addons
            - name: geoip-ipt
              mountPath: /tmp/xtables
      volumes:
        - name: xtables-addons
          hostPath:
            path: /usr/lib/xtables-addons
        - name: geoip-ipt
          hostPath:
            path: /usr/lib/x86_64-linux-gnu/xtables/
```
That seems to work for now.
But it would be great if that was not necessary :)
