### ISSUE TITLE
IPv6 pool can be configured with IPIP despite not being supported

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calicoctl#1526]
I can configure and IPv6 pool with IPIP tunneling, despite this not being supported (by the linux kernel).  
```
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: fd00::8:0/120
  spec: 
    ipip:
      enabled: true
```
We should reject this config (and document the limitation) since it doesn't work.
