### ISSUE TITLE
how to configure nat-outgoing in calico 2.1?

### ISSUE THREAD

**Issue by r0bj** [projectcalico/calicoctl#1579]
In calico 2.0 there was `ippool.yaml` to configure `nat-outgoing`:

```
ippool.yaml: |
  apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 10.200.0.0/16
  spec:
    ipip:
      enabled: true
    nat-outgoing: true
```

How to configure `nat-outgoing` in calico 2.1?

There is no mention of NAT on doc site: http://docs.projectcalico.org/v2.1/reference/node/configuration

Thanks!
