### ISSUE TITLE
docker build inside container: connection timed out

### ISSUE THREAD

**Issue by r0bj** [projectcalico/calicoctl#1613]
calico/node: v1.1.0
calico/cni: v1.6.1
kubernetes: 1.5.5
docker: 1.12.6
OS: ubuntu 14.04

Running `docker build` inside docker container failed because of connectivity issue.

Kubernetes workload:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ubuntu-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu-test
    spec:
      containers:
      - name: ubuntu-test
        image: ubuntu:16.04
        args:
        - /bin/sh
        - -c
        - while true; do sleep 3600; done
        volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
```

Inside container (install docker and prepare Dockerfile):
```
apt-get update && apt-get install -y docker.io
mkdir test && cd test
cat <<EOF > Dockerfile
FROM alpine:3.5
RUN wget -T 10 http://noc.pirx.pl/100mb.bin
EOF
```

Result:
```
# docker build -t test .
Sending build context to Docker daemon 168.6 MB
Step 1 : FROM alpine:3.5
 ---> 4a415e366388
Step 2 : RUN wget -T 10 http://noc.pirx.pl/100mb.bin
 ---> Running in e51ae496d4ce
Connecting to noc.pirx.pl (193.47.247.4:80)
wget: download timed out
The command '/bin/sh -c wget -T 10 http://noc.pirx.pl/100mb.bin' returned a non-zero code: 1
```

Connectivity from container itself works fine:
```
# wget -T 10 http://noc.pirx.pl/100mb.bin
--2017-04-20 14:20:36--  http://noc.pirx.pl/100mb.bin
Resolving noc.pirx.pl (noc.pirx.pl)... 193.47.247.4, 2a02:2780:0:100::1:4
Connecting to noc.pirx.pl (noc.pirx.pl)|193.47.247.4|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 104857600 (100M) [application/octet-stream]
Saving to: '100mb.bin'

100mb.bin           100%[===================>] 100.00M  16.5MB/s    in 7.6s

2017-04-20 14:20:44 (13.2 MB/s) - '100mb.bin' saved [104857600/104857600]
```

Networking inside container looks ok:
```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if459: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 12:bc:c2:af:60:80 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.200.138.178/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::10bc:c2ff:feaf:6080/64 scope link
       valid_lft forever preferred_lft forever
```

```
# ip r
default via 169.254.1.1 dev eth0
169.254.1.1 dev eth0  scope link
```

`docker build` works fine with standard docker installation with default networking (without calico).
It's only visible in docker container using calico networking.

I hit this issue during work on CI/DC tool which at some stage tries to build docker image.

I'm not sure where to look for solution, It may be related to how `docker build` works.

Is there any work around for that?
