### ISSUE TITLE
 ASN (unknown) for KDD w/ routing v1

### ISSUE THREAD

**Issue by frnkdny** [projectcalico/calicoctl#1625]
Setup is using calico-k8s-cluster on k8s 1.5.3. 

kubectl apply -f http://docs.projectcalico.org/v2.2/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico.yaml

export DATASTORE_TYPE=kubernetes
export KUBECONFIG=~/.kube/config

```calicoctl -l debug get node -o wide
INFO[0000] Log level set to debug                       
INFO[0000] Executing config command                     
DEBU[0000] Resources: [{{node v1} {{<nil>} } {<nil>}}]  
DEBU[0000] Data: - apiVersion: v1
  kind: node
  metadata: {}
  spec: {}
 
INFO[0000] Config file cannot be read - reading config from environment 
INFO[0000] Loading config from environment              
INFO[0000] Loaded client config: api.CalicoAPIConfigSpec{DatastoreType:"kubernetes", EtcdConfig:etcd.EtcdConfig{EtcdScheme:"http", EtcdAuthority:"127.0.0.1:2379", EtcdEndpoints:"", EtcdUsername:"", EtcdPassword:"", EtcdKeyFile:"", EtcdCertFile:"", EtcdCACertFile:""}, KubeConfig:k8s.KubeConfig{Kubeconfig:"/home/frank/.kube/config", K8sAPIEndpoint:"", K8sKeyFile:"", K8sCertFile:"", K8sCAFile:"", K8sAPIToken:"", K8sInsecureSkipTLSVerify:false}} 
DEBU[0000] Using datastore type 'kubernetes'            
DEBU[0000] Building client for config: &{Kubeconfig:/home/frank/.kube/config K8sAPIEndpoint: K8sKeyFile: K8sCertFile: K8sCAFile: K8sAPIToken: K8sInsecureSkipTLSVerify:false} 
DEBU[0000] Config overrides: &{AuthInfo:{LocationOfOrigin: ClientCertificate: ClientCertificateData:[] ClientKey: ClientKeyData:[] Token: TokenFile: Impersonate: Username: Password: AuthProvider:<nil> Extensions:map[]} ClusterDefaults:{LocationOfOrigin: Server: APIVersion: InsecureSkipTLSVerify:false CertificateAuthority: CertificateAuthorityData:[] Extensions:map[]} ClusterInfo:{LocationOfOrigin: Server: APIVersion: InsecureSkipTLSVerify:false CertificateAuthority: CertificateAuthorityData:[] Extensions:map[]} Context:{LocationOfOrigin: Cluster: AuthInfo: Namespace: Extensions:map[]} CurrentContext: Timeout:} 
DEBU[0000] Created k8s clientSet: &{DiscoveryClient:0xc4202cf7e0 CoreV1Client:0xc42040a2c0 AppsV1beta1Client:0xc42040a3d0 AuthenticationV1beta1Client:0xc42040a510 AuthorizationV1beta1Client:0xc42040a680 AutoscalingV1Client:0xc42040a7c0 BatchV1Client:0xc42040a970 BatchV2alpha1Client:0xc42040ab10 CertificatesV1alpha1Client:0xc42040ac10 ExtensionsV1beta1Client:0xc42040ad60 PolicyV1beta1Client:0xc42040ae70 RbacV1alpha1Client:0xc42040aff0 StorageV1beta1Client:0xc42040b120} 
INFO[0000] Client: &{0xc420306150}                      
DEBU[0000] Performing 'List' for {Hostname:}            
DEBU[0000] Received List request on Node type           
INFO[0000] results: {fileInvalid:false numResources:1 numHandled:1 err:<nil> singleKind:node resources:[0xc42004c680] client:0xc4201060d0} 
INFO[0000] Output in table format (wide=true)           
DEBU[0000] Performing 'Get' for GlobalBGPConfig(name=as_num) 
NAME                                                   ASN         IPV4             IPV6   
tigera-scale-fd-001                                    (unknown)   10.240.0.63/32          
tigera-scale-fd-002                                    (unknown)   10.240.0.71/32          
tigera-scale-fd-003                                    (unknown)   10.240.0.76/32          
tigera-scale-fd-004                                    (unknown)   10.240.0.73/32          
tigera-scale-fd-005                                    (unknown)   10.240.0.70/32          
tigera-scale-fd-006                                    (unknown)   10.240.0.74/32          
tigera-scale-fd-007                                    (unknown)   10.240.0.75/32          
tigera-scale-fd-008                                    (unknown)   10.240.0.64/32          
tigera-scale-fd-009                                    (unknown)   10.240.0.69/32          
tigera-scale-fd-010                                    (unknown)   10.240.0.67/32          
tigera-scale-fd-highperf-001                           (unknown)   10.240.0.79/32          
tigera-scale-fd-highperf-002                           (unknown)   10.240.0.80/32          
tigera-scale-fd-highperf-003                           (unknown)   10.240.0.78/32          
tigera-scale-fd-highperf-004                           (unknown)   10.240.0.77/32          
tigera-scale-fd-master.c.unique-caldron-775.internal   (unknown)   10.240.0.59/32          
```

Below is more context for the state of the cluster. 

calicoctl node status
```
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 10.240.0.63  | node-to-node mesh | up    | 18:11:24 | Established |
| 10.240.0.71  | node-to-node mesh | up    | 18:11:23 | Established |
| 10.240.0.76  | node-to-node mesh | up    | 18:11:23 | Established |
| 10.240.0.73  | node-to-node mesh | up    | 18:11:24 | Established |
| 10.240.0.70  | node-to-node mesh | up    | 18:11:24 | Established |
| 10.240.0.75  | node-to-node mesh | up    | 18:11:23 | Established |
| 10.240.0.64  | node-to-node mesh | up    | 18:11:23 | Established |
| 10.240.0.69  | node-to-node mesh | up    | 18:11:23 | Established |
| 10.240.0.67  | node-to-node mesh | up    | 18:11:23 | Established |
| 10.240.0.80  | node-to-node mesh | up    | 18:11:23 | Established |
| 10.240.0.78  | node-to-node mesh | up    | 18:11:23 | Established |
| 10.240.0.77  | node-to-node mesh | up    | 18:11:23 | Established |
| 10.240.0.79  | node-to-node mesh | up    | 18:11:24 | Established |
| 10.240.0.59  | node-to-node mesh | up    | 18:11:24 | Established |
+--------------+-------------------+-------+----------+-------------+
```
calicoctl get wep -o yaml
```
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    ActiveInstanceID: ""
    labels:
      calico/k8s_ns: kube-system
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
      version: v19
    name: eth0
    node: tigera-scale-fd-highperf-004
    orchestrator: k8s
    workload: kube-system.kube-dns-v19-wcnxw
  spec:
    interfaceName: calib3287f19aa1
    ipNetworks:
    - 10.244.11.2/32
    profiles:
    - ns.projectcalico.org/kube-system
```
calicoctl get ippool -o yaml
```
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 10.244.0.0/16
  spec:
    ipip:
      enabled: true
      mode: always
    nat-outgoing: true
```
calicoctl get profiles -o yaml
```
- apiVersion: v1
  kind: profile
  metadata:
    name: ns.projectcalico.org/default
  spec: {}
- apiVersion: v1
  kind: profile
  metadata:
    name: ns.projectcalico.org/kube-system
  spec: {}
```
calicoctl get policy -o yaml
```
- apiVersion: v1
  kind: policy
  metadata:
    name: np.projectcalico.org/default.nginx-service
  spec:
    ingress:
    - action: allow
      destination:
        ports:
        - 80
      protocol: tcp
      source:
        selector: calico/k8s_ns == 'default' && role == 'getter'
    order: 1000
    selector: calico/k8s_ns == 'default' && role == 'nginx-server'
- apiVersion: v1
  kind: policy
  metadata:
    name: ns.projectcalico.org/default
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
    selector: calico/k8s_ns == 'default'
- apiVersion: v1
  kind: policy
  metadata:
    name: ns.projectcalico.org/kube-system
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
    selector: calico/k8s_ns == 'kube-system'
```
