### ISSUE TITLE
Unable to connect to Kubernetes host IP from container on that host

### ISSUE THREAD

**Issue by svend** [projectcalico/calicoctl#1639]
We have two Kubernetes clusters. In cluster A, containers can ping their host. In cluster B, a ping between a container and its host times out. On both clusters, containers can ping hosts they are not running on on.

Cluster A is running quay.io/calico/node:v1.0.2 and calico/cni:v1.5.5.
Cluster B is running  quay.io/calico/node:v1.1.1 and calico/cni:v1.6.1.
Other than that, the daemonSets and calico-config configMaps are the same.

Here is how I am testing:

```
kubectl --context clusterA exec -it busybox -- ping -qc $(kubectl --context clusterA get po busybox -o 'jsonpath={.spec.nodeName}') # works
kubectl --context clusterB exec -it busybox -- ping -qc $(kubectl --context clusterB get po busybox -o 'jsonpath={.spec.nodeName}') # times out
```

A tcpdump on the cali* interface shows the ICMP requests, but no responses.

Let me know what additional information I can provide.

**Comment by tmjd** [comment]
Could you attach or link the manifest you are using?  There were some changes between Calico v2.0 and v2.1 around how the default IP Pools are created.  I feel like both scenarios should produce results where containers can ping their hosts but it might help.

**Comment by svend** [comment]
Here are the daemonset and configmap manifests. Thanks!

[calico-daemonset](https://gist.github.com/svend/b7ba40eb8b18d59f3f666dc10ba3feec)
[calico-configmap](https://gist.github.com/svend/efb22e7f73481299a6a816b12fb26bf2)

**Comment by tmjd** [comment]
Could you do a `calicoctl get pool -o yaml` for both clusters and attach that output? Thanks

**Comment by svend** [comment]
I get the same results for cluster A and B.

```$ calicoctl get pool -o yaml
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 10.7.0.0/16
  spec:
    nat-outgoing: true
```

**Comment by tmjd** [comment]
Some questions before asking for a lot of information below. 
- Have you verified that `kubectl --context clusterB get po busybox -o 'jsonpath={.spec.nodeName}'` is returning what you expect and that also that name it resolves to is what you expect?
- On cluster B do multiple hosts and pods on them show the same behavior or is this only on one host?
- Does pod to pod traffic work?
- Are you running the calico-policy-controller?

Here is the information you should check and see if you can spot an issue.  If nothing stands out then please attach this information or link to it.
If you attach the information I am a fan of doing the following so the page doesn't get too crazy
```
<details><summary>some title for the info</summary>

code block with the information

</details>
```

I would probably start with checking `calicoctl node status` on the host in question.  This will show if calico is running as expected.

Check the output the following on your host with the ping pod in both clusters:
- `ip a`
- `ip r`

Compare the output of the following from both clusters?
- `calicoctl get wep -o yaml`
- `calicoctl get profile -o yaml`
- `calicoctl get policy -o yaml`

On both clusters do the following:
1. Run `sudo iptables -Z` on the host with your busybox pod (I'm assuming the same pod as you mentioned in your original report).
2. Run the ping command you mentioned in your original report
3. Collect and attach the output of `sudo iptables-save -c`
That should let us see both the differences in the iptables rules and what rule is dropping the packets in your B cluster.

**Comment by svend** [comment]
Thanks for your help!

> Have you verified that kubectl --context clusterB get po busybox -o 'jsonpath={.spec.nodeName}' is returning what you expect and that also that name it resolves to is what you expect?

The ping output shows the expected host's IP.

> On cluster B do multiple hosts and pods on them show the same behavior or is this only on one host?

I ran the following daemonset on both clusters to test ping to the local host by IP address.

<details><summary>ping-test-daemonset.yaml</summary>

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ssorensen-ping-test
spec:
  template:
    metadata:
      labels:
        app: ssorensen-ping-test
      name: ssorensen-ping-test
    spec:
      containers:
      - name: ssorensen-ping-test
        image: busybox:1.26.2-uclibc
        command:
        - sh
        - -c
        - |
          host_ip=$(nslookup $MY_NODE_NAME | tail -1 | cut -d' ' -f 3)
          while :; do
            ping -qc 1 $host_ip
            sleep 5
          done
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 30Mi
```
</details>

On clusterA, all pods could ping the host's IP. On clusterB, the pings timed out for all pods. The outputs are below, which contain the host IPs.

<details><summary>clusterA DS output</summary>

```
kubectl --context clusterA get po -l app=ssorensen-ping-test | grep ping | awk '{print $1}' | xargs -I% kubectl --context clusterA log --tail 3 %
--- 10.150.17.180 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.072/0.072/0.072 ms
--- 10.150.17.211 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.070/0.070/0.070 ms
--- 10.150.17.123 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.074/0.074/0.074 ms
--- 10.150.17.204 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.084/0.084/0.084 ms
--- 10.150.17.9 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.088/0.088/0.088 ms
--- 10.150.17.135 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.085/0.085/0.085 ms
--- 10.150.17.37 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.072/0.072/0.072 ms
--- 10.150.17.118 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.088/0.088/0.088 ms
--- 10.150.17.168 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.089/0.089/0.089 ms
--- 10.150.17.181 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.082/0.082/0.082 ms
--- 10.150.17.64 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.077/0.077/0.077 ms
--- 10.150.17.104 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.065/0.065/0.065 ms
--- 10.150.17.206 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.076/0.076/0.076 ms
--- 10.150.17.250 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.093/0.093/0.093 ms
--- 10.150.17.208 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.092/0.092/0.092 ms
--- 10.150.17.55 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.084/0.084/0.084 ms
--- 10.150.17.6 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.082/0.082/0.082 ms
--- 10.150.17.122 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.112/0.112/0.112 ms
--- 10.150.17.45 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.081/0.081/0.081 ms
--- 10.150.17.98 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.081/0.081/0.081 ms
--- 10.150.17.244 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.066/0.066/0.066 ms
--- 10.150.17.94 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.093/0.093/0.093 ms
--- 10.150.17.115 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.070/0.070/0.070 ms
--- 10.150.17.183 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.094/0.094/0.094 ms
```
</details>

<details><summary>clusterB DS output</summary>

```
kubectl --context clusterB get po -l app=ssorensen-ping-test | grep ping | awk '{print $1}' | xargs -I% kubectl --context clusterB log --tail 3 %

--- 10.150.15.100 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.46 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.159 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.184 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.66 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.195 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.200 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.121 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.116 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.106 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.103 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.194 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.254 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.227 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.74 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.157 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.187 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

--- 10.150.15.112 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss
```
</details>

> Does pod to pod traffic work?

There are not problems with pod to pod traffic on either cluster that I can see.

> Are you running the calico-policy-controller?

We are running the calico-policy-controller on both clusters. Here is the deployment manifest, which is the same on both clusters.

<details><summary>calico-policy-controller deployment</summary>

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    logging_category: policy-controller
    logging_service: calico
    scheduler.alpha.kubernetes.io/critical-pod: ""
    scheduler.alpha.kubernetes.io/tolerations: |
      [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
       {"key": "CriticalAddonsOnly", "operator": "Exists"}]
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: calico-policy
  name: calico-policy-controller
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/calico-policy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: calico-policy
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: calico-policy
      name: calico-policy-controller
      namespace: kube-system
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: debug
        - name: CA_CERT_PATH
          valueFrom:
            configMapKeyRef:
              key: etcd_ca
              name: calico-config
        - name: ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: etcd_endpoints
              name: calico-config
        - name: ETCD_CA_CERT_FILE
          valueFrom:
            configMapKeyRef:
              key: etcd_ca
              name: calico-config
        - name: ETCD_KEY_FILE
          valueFrom:
            configMapKeyRef:
              key: etcd_key
              name: calico-config
        - name: ETCD_CERT_FILE
          valueFrom:
            configMapKeyRef:
              key: etcd_cert
              name: calico-config
        - name: K8S_API
          value: https://kubernetes.default:443
        - name: CONFIGURE_ETC_HOSTS
          value: "true"
        image: docker.util.pages/bengleman/calico/k8s-policy:v0.5.1-3
        imagePullPolicy: IfNotPresent
        name: calico-policy-controller
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /calico-secrets
          name: etcd-certs
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etcd-certs
        secret:
          defaultMode: 420
          secretName: calico-etcd-secrets
status: {}
```
</details>

I'm still gathering the rest of the information.
