### ISSUE TITLE
"Failed to apply 'policy' resource: operation Apply is not supported on Policy"

### ISSUE THREAD

**Issue by felipejfc** [projectcalico/calicoctl#1665]
I was going through the advanced policy tutorial but then when I try to apply the policy ```advanced-policy-demo.deny-egress``` :

```
calicoctl apply -f - <<EOF
apiVersion: v1
kind: policy
metadata:
  name: advanced-policy-demo.deny-egress
spec:
  selector: calico/k8s_ns == 'advanced-policy-demo'
  order: 500
  egress:
  - action: deny
    destination:
      notSelector: calico/k8s_ns == 'advanced-policy-demo'
EOF
```

I get the following error:

```
Failed to apply 'policy' resource: operation Apply is not supported on Policy(name=advanced-policy-demo.deny-egress)
```

calicoctl version:
```
calicoctl version
Version:      v1.2.1
Build date:
Git commit:   d1c370c2
```

calico version on the daemonset running on kubernetes is:
```
image: calico/node:v1.1.3
image: calico/cni:v1.8.0
```
