### ISSUE TITLE
Unknown resource type ipPool

### ISSUE THREAD

**Issue by pwzgorilla** [projectcalico/calicoctl#1798]
```
# cat ippool.yaml
```
```
apiVersion: v2
kind: ipPool
metadata:
  cidr: 10.1.0.0/16
spec:
  ipip:
    enabled: false
  nat-outgoing: true
  disabled: false
```
```
calicoctl create -f ippool.yaml
```
shows:
```
Failed to execute command: Unknown resource type (ipPool) and/or version (v2)
```

calicoctl release: calico2.0.0
