### ISSUE TITLE
calicoctl get policy $name prepends `default.` to the name

### ISSUE THREAD

**Issue by prbsparx** [projectcalico/calicoctl#2065]
Running calicoctl get policy $name adds "default." to the name

## Expected Behavior
calicoctl should get the policy by the name exactly as entered.

## Current Behavior
calicoctl prepends "default." to the policy name.

## Possible Solution
n/a

## Steps to Reproduce (for bugs)
Create a default deny network policy in Rancher v2.2.7 with the below YAML:
```
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  selector: all()
  order: 999
  types:
  - ingress
  ingress:
  - action: deny
    source: {}
```
Use `calicoctl` to read the NetworkPolicy with this command:
```calicoctl get NetworkPolicy -n "$namespace" 'default-deny' -o yaml```
When I run the command I get this output:
```resource does not exist: NetworkPolicy(REDACTED/default.default-deny) with error: networkpolicies.crd.projectcalico.org "default.default-deny" not found```

## Context
Looking at multiple calico policies in YAML view is difficult. It'd be great to be able to see the details of a single policy at a time.

## Your Environment

* calicoctl version = 3.9.0 (ab93db3b)
* Rancher v2.2.7
* Kubernetes v1.13.5
