### ISSUE TITLE
"kubectl apply -f calico.yaml"  fail

### ISSUE THREAD

**Issue by xzy256** [projectcalico/calicoctl#2103]
Hi, 
I apply calico for k8s network, but encountered error:`error decoding from json: illegal base64 data at input byte 3`. 
1. download [calico.yaml-3.11](https://docs.projectcalico.org/v3.11/getting-started/kubernetes/installation/hosted/calico.yaml)
2. edit it
```
kind: Secret
...
data:
  etcd-key: cat /etc/kubernetes/ssl/kubernetes-key.pem | base64 -w 0
  etcd-cert: cat /etc/kubernetes/ssl/kubernetes.pem | base64 -w 0
  etcd-ca: cat /etc/kubernetes/ssl/ca.pem | base64 -w 0
...
kind: ConfigMap
...
data:
  etcd_endpoints: "https://xxx:2380,https://xxx:2380,https://xxx:2380"
  etcd_ca: "/etc/kubernetes/ssl/ca.pem"
  etcd_cert: "/etc/kubernetes/ssl/kubernetes.pem"
  etcd_key: "/etc/kubernetes/ssl/kubernetes-key.pem"
```
When exec `kubectl apply -f calico.yaml`,  i get error as follow:

> The request is invalid: patch: Invalid value: "map[data:map[etcd-ca:cat /etc/kubernetes/ssl/ca.pem | base64 -w 0 etcd-cert:cat /etc/kubernetes/ssl/kubernetes.pem | base64 -w 0 etcd-key:cat /etc/kubernetes/ssl/kubernetes-key.pem | base64 -w 0] metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"v1\",\"data\":{\"etcd-ca\":\"cat /etc/kubernetes/ssl/ca.pem | base64 -w 0\",\"etcd-cert\":\"cat /etc/kubernetes/ssl/kubernetes.pem | base64 -w 0\",\"etcd-key\":\"cat /etc/kubernetes/ssl/kubernetes-key.pem | base64 -w 0\"},\"kind\":\"Secret\",\"metadata\":{\"annotations\":{},\"name\":\"calico-etcd-secrets\",\"namespace\":\"kube-system\"},\"type\":\"Opaque\"}\n]]]": error decoding from json: illegal base64 data at input byte 3

Etcd cluster is built with k8s certificates. It is healthy. How should i do for fix upper error?
```
# kubectl get cs
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok                   
controller-manager   Healthy   ok                   
etcd-0               Healthy   {"health":"true"}    
etcd-2               Healthy   {"health":"true"}    
etcd-1               Healthy   {"health": "true"}  
```
```
# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511
Codename:	Core
```
